project:
  type: default
  title: "causal_inference_r_workshop"
  render:
    - "slides/raw/*.qmd"
    - "!slides/raw/nhefs-whole-game.qmd"
  
profile:
  default: dev
  group:
    - [dev, prod]

execute:
  echo: true



