---
format: gfm
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r}
#| include: false

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Causal Inference in R Workshop

### Slides

- [00 Intro](https://causal-inference-r-workshop.netlify.app/00-intro.html)
- [01 Whole Game](https://causal-inference-r-workshop.netlify.app/01-whole-game.html)
- [03 When Standard Methods Succeed](https://causal-inference-r-workshop.netlify.app/03-when-standard-methods-succeed.html)
- [04 Causal Inference with `group_by` and `summarise`](https://causal-inference-r-workshop.netlify.app/04-causal-inference-with-group-by-and-summarise.html)
- [05 Causal Diagrams](https://causal-inference-r-workshop.netlify.app/05-dags.html)
- [06 Causal Inference is Not Just a Statistics Problem](https://causal-inference-r-workshop.netlify.app/06-quartets.html)
- [07 Causal Assumptions](https://causal-inference-r-workshop.netlify.app/07-causal-assumptions.html)
- [08 Introduction to Propensity Scores](https://causal-inference-r-workshop.netlify.app/08-pscores.html)
- [09 Using Propensity Scores](https://causal-inference-r-workshop.netlify.app/09-using-pscores.html)
- [10 Checking Propensity Scores](https://causal-inference-r-workshop.netlify.app/10-pscore-diagnostics.html)
- [11 Fitting the outcome model](https://causal-inference-r-workshop.netlify.app/11-outcome-model.html)
- [12 Continuous Exposures and G-Computation](https://causal-inference-r-workshop.netlify.app/12-continuous-g-comp.html)
- [13 Tipping Point Sensitivity Analyses](https://causal-inference-r-workshop.netlify.app/13-tipr.html)
- [14 Interaction and Heterogeneous Treatment Effects](https://causal-inference-r-workshop.netlify.app/14-interaction.html)
- [16 Bonus: Selection Bias](https://causal-inference-r-workshop.netlify.app/16-bonus-selection-bias.html)
- [17 Bonus: Continuous Exposures with Propensity Scores](https://causal-inference-r-workshop.netlify.app/17-bonus-continuous-pscores.html)
- [18 Bonus: Machine Learning for Causal Inference](https://causal-inference-r-workshop.netlify.app/18-bonus-ml-for-causal.html)

### Installing materials locally

We will provide a link to a Posit Cloud space for the workshop. However, we recommend also installing the materials locally so you have two options.

To install the required packages and course materials, we have an R package called {[causalworkshop](https://github.com/malcolmbarrett/causalworkshop)} to help you do that! You can install {[causalworkshop](https://github.com/malcolmbarrett/causalworkshop)} from GitHub with:

```r
install.packages("pak")
pak::pak("r-causal/causalworkshop")
```

Once you've installed the package, install the workshop with

```r
causalworkshop::install_workshop()
```

By default, this package downloads the materials to a conspicuous place like your Desktop. You can also tell `install_workshop()` exactly where to put the materials:

```r
causalworkshop::install_workshop("a/path/on/your/computer")
```
